apiVersion: v1
kind: Template
metadata:
  name: openshiftapp-template
  labels:
    app: openshiftapp
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: openshiftapp
      labels:
        app: openshiftapp
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: openshiftapp
      labels:
        app: openshiftapp
    spec:
      source:
        git:
          uri: https://github.com/King-Of-The-Cookies/openshift_deployment.git
      output:
        to:
          kind: ImageStreamTag
          name: openshiftapp:1
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true