apiVersion: v1
kind: Template
metadata:
  name: openshiftdeployment-deploy
  labels:
    app: openshiftapp
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: openshiftappdeployment
      labels:
        app: openshiftapp
    spec:
      strategy:
        type: Rolling
      replicas: 1
      template:
        metadata:
          name: openshiftapp
          labels:
            app: openshiftapp
            role: application
        spec:
          containers:
            - name: openshiftapp
              image: 172.30.1.1:5000/test/openshiftapp:1
              ports:
                - containerPort: 7500
                  protocol: TCP

  - apiVersion: v1
    kind: Service
    metadata:
      name: openshiftappservice
      labels:
        app: openshiftapp
    spec:
      ports:
        - name: openshiftapp-tcp
          port: 7500
          targetPort: 7500
          protocol: TCP
      selector:
        role: application